
package com.mine.product.szmtr.msgboard.message.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.0
 * 2018-12-21T16:36:10.529+08:00
 * Generated source version: 3.1.0
 */

@WebFault(name = "Exception", targetNamespace = "http://webservice.psp.szmtr.product.mine.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.mine.product.szmtr.msgboard.message.webservice.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.mine.product.szmtr.msgboard.message.webservice.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.mine.product.szmtr.msgboard.message.webservice.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.mine.product.szmtr.msgboard.message.webservice.Exception getFaultInfo() {
        return this.exception;
    }
}
