package com.mine.product.szmtr.msgboard.message.webservice;

import java.util.Map;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2018-12-21T16:36:10.532+08:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://webservice.psp.szmtr.product.mine.com/", name = "IMsgWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface IMsgWebService {

    @WebMethod
    @RequestWrapper(localName = "msgHandler", targetNamespace = "http://webservice.psp.szmtr.product.mine.com/", className = "com.mine.product.szmtr.msgboard.message.webservice.MsgHandler")
    @ResponseWrapper(localName = "msgHandlerResponse", targetNamespace = "http://webservice.psp.szmtr.product.mine.com/", className = "com.mine.product.szmtr.msgboard.message.webservice.MsgHandlerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String msgHandler(
        @WebParam(name = "arg0", targetNamespace = "")
        Map<String, String> map
    ) throws Exception_Exception;
}
